const orderTypes = {
    SET_CUSTOMER_NAME: "SET_CUSTOMER_NAME",
    SET_CATEGORY: "SET_CATEGORY",
    SET_ITEM: "SET_ITEM",
    RESET_ITEM: "RESET_ITEM",
    ADD_ITEM: "ADD_ITEM",
    RESET_ORDER: "RESET_ORDER",
    PLACE_ORDER: "PLACE_ORDER",
}

export default orderTypes